"""
RFC-037 Avenue 13: associator-load running from empirical rollout traffic.

This module replaces fixed handcrafted triple schedules with deterministic traffic
sampled from rollout payloads generated by the current update kernel.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Sequence, Tuple

import numpy as np

from calc.update_rule_ablation import e_basis, next_state_v2, oct_mul

ROOT = Path(__file__).resolve().parents[1]
POLICY_FILE_DEFAULT = Path(__file__).with_name("weinberg_associator_policies.json")
OUT_JSON = ROOT / "sources" / "weinberg_associator_running_results.json"
OUT_MD = ROOT / "sources" / "weinberg_associator_running_results.md"

IDX_E0 = 0
IDX_E1 = 1
IDX_E6 = 6
IDX_E7 = 7

MASK_EXCLUSIVE_U1 = (IDX_E0,)
MASK_U1_INCLUSIVE = (IDX_E0, IDX_E7)
MASK_WEAK = (IDX_E1, IDX_E6, IDX_E7)
MASK_EW = (IDX_E0, IDX_E1, IDX_E6, IDX_E7)


@dataclass(frozen=True)
class RolloutPolicy:
    policy_id: str
    description: str
    central_color: int          # FanoPoint 0..6
    source_colors: Tuple[int, int, int]  # three incoming source Fano labels
    source_order: str           # "asc" or "desc"
    basis_selector: str         # imag_abs_argmax | imag_pos_argmax | imag_signed_argmax
    init_mode: str              # base | ew_seed
    projection: str             # sign_clip | none


def _energy(v: np.ndarray, mask: Sequence[int]) -> float:
    sel = v[list(mask)].astype(np.float64)
    return float(np.dot(sel, sel))


def associator(a: np.ndarray, b: np.ndarray, c: np.ndarray) -> np.ndarray:
    return oct_mul(oct_mul(a, b), c) - oct_mul(a, oct_mul(b, c))


def ratio(gprime_sq: float, g_sq: float) -> float:
    d = gprime_sq + g_sq
    if d <= 0:
        raise ValueError(f"non-positive denominator in ratio: g'^2={gprime_sq}, g^2={g_sq}")
    return gprime_sq / d


def initial_node_state(color_label: int, mode: str) -> np.ndarray:
    """Simple deterministic initial state seed for one node."""
    psi = np.zeros(8, dtype=np.int64)
    psi[IDX_E0] = 1
    psi[color_label + 1] = 1
    if mode == "ew_seed":
        psi[IDX_E1] += 1
        psi[IDX_E6] += 1
        psi[IDX_E7] += 1
    elif mode != "base":
        raise ValueError(f"unknown init_mode: {mode}")
    return psi


def project_state(psi: np.ndarray, projection: str) -> np.ndarray:
    if projection == "none":
        return psi
    if projection == "sign_clip":
        out = np.zeros_like(psi)
        out[psi > 0] = 1
        out[psi < 0] = -1
        return out
    raise ValueError(f"unknown projection mode: {projection}")


def edge_op_from_color(color_label: int, psi: np.ndarray) -> np.ndarray:
    """
    Python mirror of UpdateRule.edgeOp:
      edgeOp(label, psi) = e_{label+1} * psi
    where label is FanoPoint 0..6 and basis index is 1..7.
    """
    return oct_mul(e_basis(color_label + 1), psi)


def select_message_basis_idx(msg: np.ndarray, selector: str) -> int:
    """
    Convert an octonion payload to one generator index (1..7) for associator stats.
    Deterministic tie-break: smallest index.
    """
    imag = msg[1:].astype(np.int64)

    if selector == "imag_abs_argmax":
        vals = np.abs(imag)
    elif selector == "imag_pos_argmax":
        vals = np.where(imag > 0, imag, 0)
    elif selector == "imag_signed_argmax":
        vals = imag
    else:
        raise ValueError(f"unknown basis_selector: {selector}")

    m = int(np.max(vals))
    if m == 0:
        return 7
    idx = int(np.where(vals == m)[0][0])  # deterministic tie-break
    return idx + 1


def _policy_checksum(policy: RolloutPolicy) -> str:
    payload = {
        "policy_id": policy.policy_id,
        "description": policy.description,
        "central_color": policy.central_color,
        "source_colors": list(policy.source_colors),
        "source_order": policy.source_order,
        "basis_selector": policy.basis_selector,
        "init_mode": policy.init_mode,
        "projection": policy.projection,
    }
    return hashlib.sha256(
        json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    ).hexdigest()


def load_policy_bundle(policy_file: Path | None = None) -> Dict[str, object]:
    path = policy_file or POLICY_FILE_DEFAULT
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def _parse_policies(bundle: Dict[str, object]) -> List[RolloutPolicy]:
    out: List[RolloutPolicy] = []
    for row in bundle["policies"]:
        central = int(row["central_color"])
        src = tuple(int(x) for x in row["source_colors"])
        if len(src) != 3:
            raise ValueError(f"source_colors must have length 3, got {src}")
        for c in (central, *src):
            if c < 0 or c > 6:
                raise ValueError(f"color labels must be in [0,6], got {c}")
        out.append(
            RolloutPolicy(
                policy_id=str(row["policy_id"]),
                description=str(row["description"]),
                central_color=central,
                source_colors=(src[0], src[1], src[2]),
                source_order=str(row["source_order"]),
                basis_selector=str(row["basis_selector"]),
                init_mode=str(row["init_mode"]),
                projection=str(row["projection"]),
            )
        )
    return out


def predeclared_policy_ids(policy_file: Path | None = None) -> List[str]:
    bundle = load_policy_bundle(policy_file)
    return [str(p["policy_id"]) for p in bundle["policies"]]


def _ordered_source_indices(source_order: str) -> List[int]:
    if source_order == "asc":
        return [1, 2, 3]
    if source_order == "desc":
        return [3, 2, 1]
    raise ValueError(f"unknown source_order: {source_order}")


def rollout_observed_traffic(
    policy: RolloutPolicy,
    ticks: int,
    *,
    basis_selector_override: str | None = None,
    source_order_override: str | None = None,
    init_mode_override: str | None = None,
) -> Dict[str, object]:
    """
    Generate empirical message triples from deterministic rollout traffic.

    Topology:
      one central node (index 0) receives messages from three source nodes (1..3),
      all nodes update synchronously each tick via next_state_v2.
    """
    basis_selector = basis_selector_override or policy.basis_selector
    source_order = source_order_override or policy.source_order
    init_mode = init_mode_override or policy.init_mode

    colors = [policy.central_color, *policy.source_colors]
    states = [initial_node_state(c, init_mode) for c in colors]
    ordered_sources = _ordered_source_indices(source_order)

    triples: List[Tuple[int, int, int]] = []
    payload_trace: List[List[np.ndarray]] = []

    for _ in range(ticks):
        center = states[0]

        payload_by_src = {
            i: edge_op_from_color(colors[i], states[i]) for i in (1, 2, 3)
        }
        ordered_payloads = [payload_by_src[i] for i in ordered_sources]
        payload_trace.append(ordered_payloads)

        triple = tuple(select_message_basis_idx(m, basis_selector) for m in ordered_payloads)
        triples.append((int(triple[0]), int(triple[1]), int(triple[2])))

        # Synchronous update.
        center_next = project_state(next_state_v2(center, ordered_payloads), policy.projection)
        center_msg = edge_op_from_color(colors[0], center)
        source_next = [
            project_state(next_state_v2(states[i], [center_msg]), policy.projection)
            for i in (1, 2, 3)
        ]
        states = [center_next, source_next[0], source_next[1], source_next[2]]

    return {
        "triples": triples,
        "payload_trace": payload_trace,
        "final_states": states,
        "basis_selector": basis_selector,
        "source_order": source_order,
        "init_mode": init_mode,
    }


def _triple_histogram(triples: Sequence[Tuple[int, int, int]]) -> Dict[str, int]:
    h: Dict[str, int] = {}
    for t in triples:
        key = f"{t[0]}-{t[1]}-{t[2]}"
        h[key] = h.get(key, 0) + 1
    return dict(sorted(h.items()))


def _triple_loads(triple: Tuple[int, int, int]) -> Tuple[float, float, float]:
    a, b, c = e_basis(triple[0]), e_basis(triple[1]), e_basis(triple[2])
    assoc = associator(a, b, c)
    load_ex_u1 = _energy(assoc, MASK_EXCLUSIVE_U1)
    load_u1_inc = _energy(assoc, MASK_U1_INCLUSIVE)
    load_weak = _energy(assoc, MASK_WEAK)
    return load_ex_u1, load_u1_inc, load_weak


def _series_from_load_sequence(
    loads: Sequence[Tuple[float, float, float]],
) -> List[Dict[str, float]]:
    # UV anchors from current locked masks.
    gprime_ex = 1.0
    gprime_inc = 2.0
    gweak = 3.0

    rows: List[Dict[str, float]] = [
        {
            "tick": 0.0,
            "gprime_sq_exclusive": gprime_ex,
            "gprime_sq_inclusive": gprime_inc,
            "g_sq_weak": gweak,
            "sin2_assoc_exclusive": ratio(gprime_ex, gweak),
            "sin2_assoc_inclusive": ratio(gprime_inc, gweak),
        }
    ]

    for i, (d_ex, d_inc, d_w) in enumerate(loads, start=1):
        gprime_ex += d_ex
        gprime_inc += d_inc
        gweak += d_w
        rows.append(
            {
                "tick": float(i),
                "gprime_sq_exclusive": gprime_ex,
                "gprime_sq_inclusive": gprime_inc,
                "g_sq_weak": gweak,
                "sin2_assoc_exclusive": ratio(gprime_ex, gweak),
                "sin2_assoc_inclusive": ratio(gprime_inc, gweak),
            }
        )
    return rows


def _summary(series: Sequence[Dict[str, float]]) -> Dict[str, float | bool]:
    s = [float(r["sin2_assoc_exclusive"]) for r in series]
    return {
        "initial_sin2_assoc_exclusive": s[0],
        "final_sin2_assoc_exclusive": s[-1],
        "delta_sin2_assoc_exclusive": s[-1] - s[0],
        "nonincreasing_sin2_assoc_exclusive": all(
            s[i + 1] <= s[i] + 1e-12 for i in range(len(s) - 1)
        ),
        "changed_sin2_assoc_exclusive": any(
            abs(s[i + 1] - s[i]) > 1e-12 for i in range(len(s) - 1)
        ),
    }


def triple_histogram(triples: Sequence[Tuple[int, int, int]]) -> Dict[str, int]:
    return _triple_histogram(triples)


def triple_loads(triple: Tuple[int, int, int]) -> Tuple[float, float, float]:
    return _triple_loads(triple)


def series_from_load_sequence(
    loads: Sequence[Tuple[float, float, float]],
) -> List[Dict[str, float]]:
    return _series_from_load_sequence(loads)


def summary_from_series(series: Sequence[Dict[str, float]]) -> Dict[str, float | bool]:
    return _summary(series)


def simulate_policy(
    policy: RolloutPolicy,
    ticks: int,
    *,
    basis_selector_override: str | None = None,
    source_order_override: str | None = None,
    init_mode_override: str | None = None,
) -> Dict[str, object]:
    traffic = rollout_observed_traffic(
        policy,
        ticks,
        basis_selector_override=basis_selector_override,
        source_order_override=source_order_override,
        init_mode_override=init_mode_override,
    )
    triples = traffic["triples"]
    loads = [_triple_loads(t) for t in triples]

    # Sequential running from observed per-tick loads.
    seq_series = _series_from_load_sequence(loads)

    # Reconstructed running from empirical triple-frequency averages.
    if ticks > 0:
        avg_ex = float(sum(x[0] for x in loads) / ticks)
        avg_inc = float(sum(x[1] for x in loads) / ticks)
        avg_w = float(sum(x[2] for x in loads) / ticks)
    else:
        avg_ex = avg_inc = avg_w = 0.0
    empirical_series = _series_from_load_sequence([(avg_ex, avg_inc, avg_w)] * ticks)

    tick_load_rows = [
        {
            "tick": float(i + 1),
            "exclusive_u1": x[0],
            "u1_inclusive": x[1],
            "weak": x[2],
        }
        for i, x in enumerate(loads)
    ]

    return {
        "policy_id": policy.policy_id,
        "policy_description": policy.description,
        "policy_checksum": _policy_checksum(policy),
        "ticks": ticks,
        "basis_selector": traffic["basis_selector"],
        "source_order": traffic["source_order"],
        "init_mode": traffic["init_mode"],
        "triples_seq": [list(t) for t in triples],
        "triple_histogram": _triple_histogram(triples),
        "tick_loads": tick_load_rows,
        "mean_tick_loads": {
            "exclusive_u1": avg_ex,
            "u1_inclusive": avg_inc,
            "weak": avg_w,
        },
        "series_seq": seq_series,
        "series_empirical_avg": empirical_series,
        "summary_seq": _summary(seq_series),
        "summary_empirical_avg": _summary(empirical_series),
    }


def run_all(policy_file: Path | None = None) -> Dict[str, object]:
    bundle = load_policy_bundle(policy_file)
    ticks = int(bundle["ticks"])
    policies = _parse_policies(bundle)
    rows = [simulate_policy(p, ticks=ticks) for p in policies]
    return {
        "rfc": "RFC-037",
        "avenue": "A13",
        "target_scale": bundle["target"]["scale"],
        "target_sin2_theta_w": float(bundle["target"]["sin2_theta_w"]),
        "initial_state": str(bundle["initial_state"]),
        "ticks": ticks,
        "rows": rows,
    }


def render_markdown(payload: Dict[str, object]) -> str:
    lines = [
        "# RFC-037 Avenue 13 Associator-Running Results",
        "",
        "Traffic source: deterministic rollout payloads (not handcrafted triple schedules).",
        f"Target: sin^2(theta_W) = {payload['target_sin2_theta_w']:.8f} at scale {payload['target_scale']}",
        f"Initial state mode: `{payload['initial_state']}`",
        f"Ticks: `{payload['ticks']}`",
        "",
        "| Policy | Seq initial | Seq final | Seq delta | Seq nonincreasing | Empirical final |",
        "|---|---:|---:|---:|---|---:|",
    ]
    for row in payload["rows"]:
        s = row["summary_seq"]
        e = row["summary_empirical_avg"]
        lines.append(
            "| {pid} | {i:.8f} | {f:.8f} | {d:+.8f} | {n} | {ef:.8f} |".format(
                pid=row["policy_id"],
                i=s["initial_sin2_assoc_exclusive"],
                f=s["final_sin2_assoc_exclusive"],
                d=s["delta_sin2_assoc_exclusive"],
                n=s["nonincreasing_sin2_assoc_exclusive"],
                ef=e["final_sin2_assoc_exclusive"],
            )
        )

    lines.extend(
        [
            "",
            "## Interpretation",
            "- `series_seq` uses per-tick observed rollout triples.",
            "- `series_empirical_avg` reconstructs running from empirical triple frequencies (mean tick loads).",
            "- This branch is still a mechanism probe, not a promoted derivation.",
        ]
    )
    return "\n".join(lines) + "\n"


def write_artifacts(payload: Dict[str, object]) -> None:
    OUT_JSON.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    OUT_MD.write_text(render_markdown(payload), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="RFC-037 Avenue 13 empirical associator-running")
    parser.add_argument("--json", action="store_true", help="Emit JSON to stdout.")
    parser.add_argument("--no-write", action="store_true", help="Do not write artifacts.")
    args = parser.parse_args()

    payload = run_all(POLICY_FILE_DEFAULT)
    if not args.no_write:
        write_artifacts(payload)
        print(f"Wrote {OUT_JSON}")
        print(f"Wrote {OUT_MD}")
    if args.json:
        print(json.dumps(payload, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
