"""Export the canonical v3 Octavian-240 alphabet to CSV."""

from __future__ import annotations

import argparse
import csv
from fractions import Fraction
from pathlib import Path
from typing import Sequence

from cog_v3.python import kernel_octavian240_multiplicative_v1 as k


ROOT = Path(__file__).resolve().parents[2]
OUT_CSV = ROOT / "cog_v3" / "sources" / "v3_octavian240_elements_v1.csv"


def _element_order(elem_id: int) -> int:
    # Multiplicative order: smallest n > 0 such that elem_id^n = identity.
    cur = int(elem_id)
    order = 1
    while cur != k.IDENTITY_ID:
        cur = int(k.multiply_ids(cur, int(elem_id)))
        order += 1
        if order > 4096:
            raise RuntimeError(f"Order search exceeded bound for elem_id={elem_id}")
    return order


def _power_orbit_group(elem_id: int, order: int) -> tuple[int, ...]:
    # Cyclic subgroup generated by elem_id, expressed as sorted ids for stable CSV.
    cur = k.IDENTITY_ID
    orbit_ids: list[int] = [int(cur)]
    for _ in range(1, int(order)):
        cur = int(k.multiply_ids(cur, int(elem_id)))
        orbit_ids.append(int(cur))
    return tuple(sorted(set(orbit_ids)))


def _power(elem_id: int, exponent: int) -> int:
    if exponent < 0:
        raise ValueError("Exponent must be non-negative.")
    cur = int(k.IDENTITY_ID)
    for _ in range(int(exponent)):
        cur = int(k.multiply_ids(cur, int(elem_id)))
    return int(cur)


def _support_mask(oct_elem: tuple) -> int:
    mask = 0
    for idx, coeff in enumerate(oct_elem):
        if coeff != 0:
            mask |= (1 << idx)
    return int(mask)


def _family_tag(support_size: int, has_e000: bool) -> str:
    if support_size == 1:
        return "A16_basis_signed_unit"
    if support_size == 4 and has_e000:
        return "B112_line_plus_e000_halfsum"
    if support_size == 4 and not has_e000:
        return "C112_complement_halfsum"
    return "other"


def _g2_proxy_tag(support_size: int, has_e000: bool, family_tag: str) -> str:
    if support_size == 1 and has_e000:
        return "G2_proxy_scalar2"
    if support_size == 1 and not has_e000:
        return "G2_proxy_pure_imag14"
    if family_tag == "B112_line_plus_e000_halfsum":
        return "G2_proxy_B112"
    if family_tag == "C112_complement_halfsum":
        return "G2_proxy_C112"
    return "G2_proxy_other"


def _rows() -> Sequence[dict[str, str]]:
    records: list[dict[str, object]] = []
    neg_one = (
        Fraction(-1, 1),
        Fraction(0, 1),
        Fraction(0, 1),
        Fraction(0, 1),
        Fraction(0, 1),
        Fraction(0, 1),
        Fraction(0, 1),
        Fraction(0, 1),
    )
    neg_one_id = int(k.ALPHABET_INDEX[neg_one])

    for elem_id, oct_elem in enumerate(k.ALPHABET):
        order = _element_order(int(elem_id))
        orbit = _power_orbit_group(int(elem_id), int(order))
        support_size = sum(1 for c in oct_elem if c != 0)
        mask = _support_mask(oct_elem)
        has_e000 = oct_elem[0] != 0
        has_e111 = oct_elem[7] != 0
        nonzero_basis = "|".join(
            k.BASIS_LABELS[idx] for idx, c in enumerate(oct_elem) if c != 0
        )
        pos_count = sum(1 for c in oct_elem if c > 0)
        neg_count = sum(1 for c in oct_elem if c < 0)
        sum_coeff = sum(oct_elem)
        sum_abs_coeff = sum(abs(c) for c in oct_elem)
        inverse_id = _power(int(elem_id), int(order - 1))
        square_id = _power(int(elem_id), 2)
        cube_id = _power(int(elem_id), 3)
        is_self_inverse = (square_id == int(k.IDENTITY_ID))
        orbit_rep_id = min(orbit)
        orbit_index = orbit.index(int(elem_id))
        norm_scalar = k.oct_norm_scalar(oct_elem)
        family_tag = _family_tag(int(support_size), bool(has_e000))
        neg_id = int(k.multiply_ids(int(elem_id), int(neg_one_id)))
        g2_tag = _g2_proxy_tag(int(support_size), bool(has_e000), family_tag)
        rec: dict[str, object] = {
            "id": int(elem_id),
            "label": k.elem_label(int(elem_id)),
            "convention_id": k.CONVENTION_ID,
            "kernel_profile": k.KERNEL_PROFILE,
            "order": int(order),
            "orbit_size": int(len(orbit)),
            "orbit_rep_id": int(orbit_rep_id),
            "orbit_index": int(orbit_index),
            "orbit_group": orbit,
            "support_size": int(support_size),
            "support_mask_bin": format(int(mask), "08b"),
            "support_mask_hex": hex(int(mask)),
            "nonzero_basis": nonzero_basis,
            "has_e000": bool(has_e000),
            "has_e111": bool(has_e111),
            "coeff_pos_count": int(pos_count),
            "coeff_neg_count": int(neg_count),
            "sum_coeff": sum_coeff,
            "sum_abs_coeff": sum_abs_coeff,
            "norm_scalar": norm_scalar,
            "family_tag": family_tag,
            "g2_proxy_tag": g2_tag,
            "inverse_id": int(inverse_id),
            "square_id": int(square_id),
            "cube_id": int(cube_id),
            "neg_id": int(neg_id),
            "is_self_inverse": bool(is_self_inverse),
        }
        for basis_idx, basis_label in enumerate(k.BASIS_LABELS):
            rec[basis_label] = oct_elem[basis_idx]
        records.append(rec)

    # Build class maps for additional orbit notions.
    order_groups: dict[int, list[int]] = {}
    family_groups: dict[str, list[int]] = {}
    g2_groups: dict[str, list[int]] = {}
    for rec in records:
        eid = int(rec["id"])
        order_groups.setdefault(int(rec["order"]), []).append(eid)
        family_groups.setdefault(str(rec["family_tag"]), []).append(eid)
        g2_groups.setdefault(str(rec["g2_proxy_tag"]), []).append(eid)

    inverse_ids = {int(rec["id"]): int(rec["inverse_id"]) for rec in records}

    # Inner-conjugation orbit sizes (left- and right-associated variants).
    inner_conj_l_size: dict[int, int] = {}
    inner_conj_r_size: dict[int, int] = {}
    all_ids = [int(rec["id"]) for rec in records]
    for x in all_ids:
        lset: set[int] = set()
        rset: set[int] = set()
        for g in all_ids:
            g_inv = inverse_ids[g]
            lval = int(k.multiply_ids(int(k.multiply_ids(g, x)), g_inv))  # (g*x)*g^-1
            rval = int(k.multiply_ids(g, int(k.multiply_ids(x, g_inv))))  # g*(x*g^-1)
            lset.add(lval)
            rset.add(rval)
        inner_conj_l_size[x] = int(len(lset))
        inner_conj_r_size[x] = int(len(rset))

    out: list[dict[str, str]] = []
    for rec in records:
        eid = int(rec["id"])
        orbit = tuple(int(x) for x in rec["orbit_group"])  # type: ignore[assignment]
        order_group = sorted(order_groups[int(rec["order"])])
        family_group = sorted(family_groups[str(rec["family_tag"])])
        g2_group = sorted(g2_groups[str(rec["g2_proxy_tag"])])
        neg_group = sorted({eid, int(rec["neg_id"])})
        inv_group = sorted({eid, int(rec["inverse_id"])})
        row: dict[str, str] = {
            "id": str(eid),
            "label": str(rec["label"]),
            "convention_id": str(rec["convention_id"]),
            "kernel_profile": str(rec["kernel_profile"]),
            "order": str(int(rec["order"])),
            "orbit_size": str(int(rec["orbit_size"])),
            "orbit_rep_id": str(int(rec["orbit_rep_id"])),
            "orbit_index": str(int(rec["orbit_index"])),
            "orbit_group": "|".join(str(int(x)) for x in orbit),
            "orbit_group_negation": "|".join(str(int(x)) for x in neg_group),
            "orbit_group_inverse": "|".join(str(int(x)) for x in inv_group),
            "orbit_group_order_class": "|".join(str(int(x)) for x in order_group),
            "orbit_group_family_class": "|".join(str(int(x)) for x in family_group),
            "orbit_group_g2_proxy_class": "|".join(str(int(x)) for x in g2_group),
            "inner_conj_l_orbit_size": str(int(inner_conj_l_size[eid])),
            "inner_conj_r_orbit_size": str(int(inner_conj_r_size[eid])),
            "support_size": str(int(rec["support_size"])),
            "support_mask_bin": str(rec["support_mask_bin"]),
            "support_mask_hex": str(rec["support_mask_hex"]),
            "nonzero_basis": str(rec["nonzero_basis"]),
            "has_e000": str(bool(rec["has_e000"])).lower(),
            "has_e111": str(bool(rec["has_e111"])).lower(),
            "coeff_pos_count": str(int(rec["coeff_pos_count"])),
            "coeff_neg_count": str(int(rec["coeff_neg_count"])),
            "sum_coeff": str(rec["sum_coeff"]),
            "sum_abs_coeff": str(rec["sum_abs_coeff"]),
            "norm_scalar": str(rec["norm_scalar"]),
            "family_tag": str(rec["family_tag"]),
            "g2_proxy_tag": str(rec["g2_proxy_tag"]),
            "inverse_id": str(int(rec["inverse_id"])),
            "square_id": str(int(rec["square_id"])),
            "cube_id": str(int(rec["cube_id"])),
            "neg_id": str(int(rec["neg_id"])),
            "is_self_inverse": str(bool(rec["is_self_inverse"])).lower(),
        }
        for basis_label in k.BASIS_LABELS:
            row[basis_label] = str(rec[basis_label])
        out.append(row)
    return out


def build_csv(out_csv: Path) -> Path:
    rows = _rows()
    out_csv.parent.mkdir(parents=True, exist_ok=True)
    fields = [
        "id",
        "label",
        "convention_id",
        "kernel_profile",
        "order",
        "orbit_size",
        "orbit_rep_id",
        "orbit_index",
        "orbit_group",
        "orbit_group_negation",
        "orbit_group_inverse",
        "orbit_group_order_class",
        "orbit_group_family_class",
        "orbit_group_g2_proxy_class",
        "inner_conj_l_orbit_size",
        "inner_conj_r_orbit_size",
        "support_size",
        "support_mask_bin",
        "support_mask_hex",
        "nonzero_basis",
        "has_e000",
        "has_e111",
        "coeff_pos_count",
        "coeff_neg_count",
        "sum_coeff",
        "sum_abs_coeff",
        "norm_scalar",
        "family_tag",
        "g2_proxy_tag",
        "inverse_id",
        "square_id",
        "cube_id",
        "neg_id",
        "is_self_inverse",
        *k.BASIS_LABELS,
    ]
    with out_csv.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)
    return out_csv


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Export v3 Octavian-240 alphabet to CSV.")
    p.add_argument(
        "--out-csv",
        type=str,
        default=str(OUT_CSV),
        help="Output CSV path.",
    )
    return p.parse_args()


def main() -> None:
    args = parse_args()
    out_path = Path(args.out_csv).resolve()
    written = build_csv(out_path)
    print(f"Wrote {written}")
    print(f"alphabet_size={k.ALPHABET_SIZE}")


if __name__ == "__main__":
    main()
